### ISSUE TITLE
Not sure what to label it but question

### ISSUE THREAD

**Issue by Dondor-sudo** [Secuter/SecuterYGOCustomCards#2]
Why is phantom skyblaster completely banned on the list, does any of the new cards abuse it that much

Also amazing job on everything here, best custom cards i have ever seen

**Comment by Secuter** [comment]
No, it's because I didn't like having generic cards limited to 1 if there is no special interaction that needs them at 1.
I changed some of them to either 0 or 3. E.g. I changed Pankratops back to 3 and banned some that may be abuseable like Phantom Skyblaster or Card of Demise.
But maybe Phantom Skyblaster could also be at 3, I don't think it's currently abusable. Even at 1, it's not played that much.

**Comment by Dondor-sudo** [comment]
Makes sense, you have been doing a really good job with balance
all interesting playstyle+virtually no floodgates+generic instant win blow outs and the support for pre existing archetypes being super fun continue the good work!
